---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
- type: heading
  label: Content
- type: directory
  path: content/projects
  label: Projects
  create: documents
  match: "**/*"
  templates:
  - projects
- type: document
  path: content/data/authors.yaml
  label: Author List
- type: heading
  label: Pages
- type: document
  path: content/data/info.json
  label: Resume
upload_dir: src/images
public_path: "/src/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm forestry-preview
